version: '3'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - node-app 
      - node-app1
      - node-app2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9090:9090"  
  node-app:
    build: .
    ports:
      - "3000:80"
  node-app1:
    build: .
    ports:
      - "3001:80"
  node-app2:
    build: .
    ports:
      - "3002:80"
